# ==============================================================================
# met_optimize_alpha_rc.R
#
# OptiSparseMET version of optimize_alpha_rc() from OptiDesign.
# The met_ prefix prevents namespace conflicts when both packages are loaded.
# Function body is identical to optimize_alpha_rc(). Only the name and all
# internal met_ call references change.
# ==============================================================================

#' Search for a criterion-optimal alpha-lattice design
#'
#' @description
#' `met_optimize_alpha_rc()` is the OptiSparseMET version of
#' `optimize_alpha_rc()` from the OptiDesign package. The `met_` prefix avoids
#' namespace conflicts when both packages are loaded simultaneously. All
#' arguments, return values, and internal logic are identical to
#' `optimize_alpha_rc()` in OptiDesign.
#'
#' `met_optimize_alpha_rc()` wraps [met_alpha_rc_stream()] and
#' [met_evaluate_alpha_efficiency()] in an optimisation loop that searches for
#' the design with the best optimality criterion value among many candidate
#' randomisations. Three search strategies are available:
#'
#' - **RS** (Random Restart): generate `n_restarts` independent designs and
#'   return the best by criterion value.
#' - **SA** (Simulated Annealing): start from a random design and iteratively
#'   propose entry permutation swaps, accepting improvements always and
#'   degradations with probability \eqn{\exp(-\Delta / T)}, where \eqn{T}
#'   cools from `sa_temp_start` to `sa_temp_end` over `sa_max_iter`
#'   iterations. Repeated across `n_restarts` independent restarts.
#' - **GA** (Genetic Algorithm): maintain a population of `ga_pop_size` entry
#'   permutations and evolve it using tournament selection, Order Crossover
#'   (OX1), random swap mutation, and elitism.
#'
#' **Constraint preservation**: all candidate designs are generated by
#' [met_alpha_rc_stream()], so family/cluster adjacency structure, genetic
#' dispersion, check placement, and alpha-lattice block balance are preserved
#' by construction in all three methods - no penalty terms are required.
#'
#' **Integrity guarantee**: every candidate design passes a structural
#' integrity check before being scored or stored as the best. The running best
#' is only updated when both the criterion score improves and a re-check
#' passes. A final integrity check is performed on the stored best before
#' returning to the user. If no valid design is found after all iterations,
#' an emergency fallback returns a single freshly constructed valid design.
#'
#' @details
#' ## Optimisation target
#'
#' All methods minimise an internal score (lower = better internally):
#'
#' | `criterion` | Internal score | Direction |
#' |-------------|---------------|-----------|
#' | `"A"` | `A_criterion` | Lower is better |
#' | `"D"` | `D_criterion` | Lower is better |
#' | `"both"` | Mean of `A_criterion` and `D_criterion` | Lower is better |
#' | `"CDmean"` | Negated CDmean | Higher CDmean is better |
#'
#' For `"CDmean"`, the internal negation is transparent to the user:
#' `best_score` and `score_history` in the output are always reported as
#' positive CDmean values (higher = better). Requires
#' `treatment_effect = "random"`.
#'
#' ## Entry permutation encoding
#'
#' For SA and GA, designs are encoded as permutations of
#' `seq_along(entry_treatments)`. A permutation is applied by passing
#' `entry_treatments[perm]` and `entry_families[perm]` to
#' [met_alpha_rc_stream()], which then randomises and allocates entries
#' according to its internal logic. This means the permutation influences the
#' treatment-to-block assignment while [met_alpha_rc_stream()] handles all
#' within-block arrangement, check placement, and dispersion.
#'
#' ## Integrity checking strategy
#'
#' Three structural constraints are verified for every candidate design:
#'
#' 1. No entry appears more than once within any replicate.
#' 2. All expected entry treatments are present in the field book.
#' 3. All check treatments are present and correctly flagged as checks.
#'
#' These checks are performed at four points in the pipeline:
#'
#' \describe{
#'   \item{Point 1 - after construction}{Inside `run_pipeline()`, immediately
#'     after [met_alpha_rc_stream()] returns. Failures discard the candidate
#'     before scoring.}
#'   \item{Point 2 - before storing as best}{Inside `.update_best()`, as a
#'     second independent check. Prevents a candidate that passed Point 1 from
#'     being stored if its state was corrupted between construction and
#'     comparison.}
#'   \item{Point 3 - final check before return}{After the optimisation loop
#'     ends, the stored best is re-checked one final time. If it fails, the
#'     emergency fallback is triggered.}
#'   \item{Point 4 - emergency fallback}{If no valid design is found, up to
#'     10 fresh random constructions are attempted. The first valid one is
#'     returned with a warning. If all 10 fail, the function stops with a
#'     diagnostic message.}
#' }
#'
#' ## Failure handling by method
#'
#' **RS**: failed restarts (construction error or integrity failure) are
#' counted and reported. If the failure rate exceeds `max_failure_rate_rs`,
#' the function stops with a diagnostic message. Below the threshold a warning
#' is issued.
#'
#' **SA**: invalid swap proposals (NULL candidate) are counted per restart but
#' are treated as neutral events - the current design is retained, the
#' temperature counter advances, and the Metropolis acceptance logic is
#' **not** invoked. This prevents invalid proposals from distorting the
#' acceptance rate. If the invalid rate within a restart exceeds
#' `max_failure_rate_sa`, a per-restart warning is issued.
#'
#' **GA**: when an offspring fails integrity, up to `ga_invalid_retries` fresh
#' random permutations are tried as replacements. This prevents population
#' slots from being occupied by `Inf`-fitness placeholders that waste
#' tournament selection capacity. The total count of invalid offspring is
#' reported in a warning and stored in `$optimization$n_failed`.
#'
#' ## Simulated Annealing temperature schedule
#'
#' - `"exponential"`: \eqn{T_k = T_0 \cdot \alpha^k} where
#'   \eqn{\alpha = (T_\text{end} / T_0)^{1 / \text{max\_iter}}}
#' - `"linear"`: \eqn{T_k} decreases linearly from `sa_temp_start` to
#'   `sa_temp_end` over `sa_max_iter` steps
#'
#' ## Genetic Algorithm operators
#'
#' - **Selection**: tournament of size 2 over valid (finite-fitness)
#'   individuals only
#' - **Crossover**: Order Crossover (OX1) - always produces a valid
#'   permutation of `seq_along(entry_treatments)`
#' - **Mutation**: random swap of two positions in the permutation
#' - **Elitism**: top `ga_elitism` individuals copied unchanged to next
#'   generation
#'
#' @param check_treatments,check_families,entry_treatments,entry_families,n_reps,n_rows,n_cols,order,serpentine,seed,attempts,warn_and_correct,fix_rows,cluster_source,GRM,A,id_map,cluster_method,cluster_seed,cluster_attempts,n_pcs_use,n_blocks_per_rep,min_block_size,max_block_size,check_placement,check_position_pattern,use_dispersion,dispersion_source,dispersion_radius,dispersion_iters,dispersion_seed,K,line_id_map
#'   Passed directly to [met_alpha_rc_stream()]. See that function for full
#'   documentation.
#'
#' @param treatment_effect,prediction_type,check_as_fixed,residual_structure,rho_row,rho_col,varcomp,spatial_engine,dense_max_n,eff_trace_samples,eff_full_max
#'   Passed directly to [met_evaluate_alpha_efficiency()]. See that function for
#'   full documentation.
#'
#' @param method Character. Optimisation method:
#' \describe{
#'   \item{`"RS"`}{Random Restart. Generates `n_restarts` independent designs
#'     and returns the one with the best criterion score. Simple, parallelisable,
#'     and robust - every candidate is a fully valid design by construction.}
#'   \item{`"SA"`}{Simulated Annealing. Iteratively proposes entry permutation
#'     swaps, accepting improvements always and degradations with a
#'     temperature-governed probability. Repeated across `n_restarts`
#'     independent restarts. Better at escaping local optima than pure random
#'     restart.}
#'   \item{`"GA"`}{Genetic Algorithm. Maintains a population of entry
#'     permutations and evolves it using OX1 crossover, swap mutation, and
#'     elitism. Most powerful global search but also most computationally
#'     intensive.}
#' }
#'
#' @param criterion Character. Optimality criterion to drive the search:
#' \describe{
#'   \item{`"A"`}{Minimise `A_criterion` (mean pairwise contrast variance for
#'     fixed effects; mean PEV for random effects). Valid for both
#'     `treatment_effect = "fixed"` and `"random"`. Recommended default.}
#'   \item{`"D"`}{Minimise `D_criterion` (geometric mean of contrast
#'     covariance eigenvalues). Fixed effects only. Falls back to
#'     `A_criterion` with a warning for random effects.}
#'   \item{`"both"`}{Minimise the mean of `A_criterion` and `D_criterion`.
#'     Fixed effects only. Falls back to `A_criterion` when D is unavailable.}
#'   \item{`"CDmean"`}{Maximise CDmean (mean coefficient of determination for
#'     GEBV prediction; Rincent et al. 2012). Requires
#'     `treatment_effect = "random"` and
#'     `prediction_type %in% c("IID", "GBLUP", "PBLUP")`. Best suited for
#'     optimising training population designs for genomic selection.}
#' }
#'
#' @param n_restarts Positive integer. Number of independent random restarts.
#'   Used by all three methods: RS runs `n_restarts` full designs; SA and GA
#'   each restart their search `n_restarts` times from a new random initial
#'   design.
#'
#' @param sa_max_iter Positive integer. Number of swap proposals per SA
#'   restart. Each proposal that produces a valid design undergoes Metropolis
#'   acceptance; invalid proposals are counted but do not affect the
#'   acceptance logic.
#'
#' @param sa_temp_start Positive numeric. Initial SA temperature \eqn{T_0}.
#'   Higher values allow more degrading moves to be accepted early in the
#'   search, improving escape from local optima at the cost of less directed
#'   search.
#'
#' @param sa_temp_end Positive numeric. Final SA temperature. Must be strictly
#'   less than `sa_temp_start`. Low values ensure the search converges to a
#'   local optimum by the end of each restart.
#'
#' @param sa_cooling Character. SA cooling schedule:
#' \describe{
#'   \item{`"exponential"`}{Geometric decay:
#'     \eqn{T_k = T_0 \cdot (T_\text{end}/T_0)^{k/\text{max\_iter}}}.
#'     Recommended - spends more iterations at low temperature where
#'     refinement occurs.}
#'   \item{`"linear"`}{Linear decay from `sa_temp_start` to `sa_temp_end`.}
#' }
#'
#' @param sa_swap_scope Character. Scope of entry swap proposals during SA:
#' \describe{
#'   \item{`"global"`}{Any two non-check entries anywhere in the design may
#'     be swapped. Has the largest impact on the criterion because it changes
#'     which entries co-occur in blocks across replicates. Recommended for
#'     most use cases.}
#'   \item{`"within_rep"`}{Swaps restricted to entries within the same
#'     replicate. Preserves rep-level balance but limits criterion improvement
#'     compared with global swaps.}
#'   \item{`"within_block"`}{Swaps restricted to entries within the same
#'     incomplete block. Has minimal criterion impact under IID residuals
#'     because the C matrix is invariant to within-block reordering. Only
#'     marginally useful under strong spatial correlation (AR1, AR1xAR1).}
#' }
#'
#' @param ga_pop_size Positive integer \eqn{\geq 4}. Number of individuals in
#'   the GA population. Larger populations improve coverage of the design
#'   space but increase the cost per generation linearly.
#'
#' @param ga_n_generations Positive integer. Number of GA generations per run.
#'   Each generation evaluates up to `ga_pop_size - ga_elitism` new offspring.
#'
#' @param ga_crossover_rate Numeric in \eqn{[0, 1]}. Probability of applying
#'   OX1 crossover to produce an offspring. When crossover is not applied, the
#'   first parent's permutation is passed directly to mutation. Values between
#'   0.6 and 0.9 are typical.
#'
#' @param ga_mutation_rate Numeric in \eqn{[0, 1]}. Probability of applying a
#'   random swap mutation to an offspring permutation. Provides diversity;
#'   values between 0.1 and 0.3 are typical.
#'
#' @param ga_elitism Non-negative integer strictly less than `ga_pop_size`.
#'   Number of best individuals copied unchanged to the next generation.
#'   Prevents loss of the best solution found so far. Values of 1 or 2 are
#'   usually sufficient.
#'
#' @param max_failure_rate_rs Numeric in \eqn{[0, 1]}. Maximum tolerated
#'   fraction of RS restarts that may fail construction or integrity checking
#'   before the function stops with a diagnostic error. Default `0.5` (stop
#'   if more than half of restarts fail). Below this threshold a warning is
#'   issued instead. Increase for very constrained field geometries where some
#'   failure is expected.
#'
#' @param max_failure_rate_sa Numeric in \eqn{[0, 1]}. Maximum tolerated
#'   fraction of SA swap proposals per restart that may produce invalid
#'   designs before a per-restart warning is issued. Default `0.2`. This does
#'   not stop the function - it is informational. Invalid swaps are counted but
#'   treated as neutral (the current design is retained without invoking the
#'   Metropolis criterion).
#'
#' @param ga_invalid_retries Non-negative integer. Number of additional random
#'   permutation attempts made when a GA offspring fails integrity checking.
#'   Default `3`. If all retries also fail, the population slot receives
#'   `Inf` fitness and participates in no future tournament selection.
#'
#' @param verbose_opt Logical. If `TRUE`, prints per-restart or per-generation
#'   progress messages including current score, running best, and failure
#'   counts. Set to `FALSE` for batch or parallel runs.
#'
#' @return The return value of [met_alpha_rc_stream()] for the best valid design
#'   found, augmented with two additional top-level components:
#' \describe{
#'   \item{`efficiency`}{The full output of [met_evaluate_alpha_efficiency()]
#'     for the best design, including all applicable criterion values:
#'     `A_criterion`, `D_criterion`, `A_efficiency`, `D_efficiency`,
#'     `CDmean`, and `CD_per_line`.}
#'   \item{`optimization`}{Named list of optimisation metadata:
#'     \describe{
#'       \item{`method`}{Character. `"RS"`, `"SA"`, or `"GA"`.}
#'       \item{`criterion`}{Character. As supplied.}
#'       \item{`best_score`}{Numeric. Best criterion value found, reported in
#'         the natural direction for the user. For `criterion = "A"`, `"D"`,
#'         or `"both"`: lower is better. For `criterion = "CDmean"`: higher
#'         is better (positive value, negation is internal only).}
#'       \item{`score_history`}{For RS and GA: numeric vector of length
#'         `n_restarts` or `ga_n_generations` respectively, tracking the best
#'         criterion value at each step. `NA` entries indicate failed
#'         iterations. For SA: a list of `n_restarts` numeric vectors, each
#'         of length `sa_max_iter`, tracking the current score at each
#'         iteration within that restart. For `criterion = "CDmean"`, all
#'         values are reported as positive CDmean.}
#'       \item{`master_seed`}{Integer. The master random seed used.}
#'       \item{`n_failed`}{Integer. Number of failed candidates (RS: failed
#'         restarts; SA: failed initial designs across restarts; GA: total
#'         invalid offspring requiring retry or fallback to `Inf` fitness).
#'         `NA` if not tracked for the method.}
#'       \item{`n_restarts`}{Integer or `NULL`. The value of `n_restarts`.
#'         RS only; `NULL` for SA and GA.}
#'       \item{`sa_params`}{Named list or `NULL`. SA parameters:
#'         `n_restarts`, `max_iter`, `temp_start`, `temp_end`, `cooling`,
#'         `swap_scope`. SA only.}
#'       \item{`ga_params`}{Named list or `NULL`. GA parameters: `pop_size`,
#'         `n_generations`, `crossover_rate`, `mutation_rate`, `elitism`,
#'         `invalid_retries`. GA only.}
#'     }
#'   }
#' }
#'
#' If no valid optimised design is found after all iterations, a warning is
#' issued and the function returns a single freshly constructed valid design
#' via the emergency fallback (see **Integrity checking strategy** above). If
#' even the emergency fallback fails after 10 attempts, the function stops
#' with an informative error message.
#'
#' @references
#' Rincent, R., Laloe, D., Nicolas, S., Altmann, T., Brunel, D., Revilla, P.,
#' ... & Moreau, L. (2012). Maximizing the reliability of genomic selection by
#' optimizing the calibration set of reference individuals: comparison of
#' methods in two diverse groups of maize inbreds (*Zea mays* L.).
#' *Genetics*, 192(2), 715-728.
#'
#' Jones, B., Allen-Moyer, K., & Goos, P. (2021). A-optimal versus D-optimal
#' design of screening experiments. *Journal of Quality Technology*, 53(4),
#' 369-382.
#'
#' Kirkpatrick, S., Gelatt, C. D., & Vecchi, M. P. (1983). Optimization by
#' simulated annealing. *Science*, 220(4598), 671-680.
#'
#' Holland, J. H. (1992). *Adaptation in Natural and Artificial Systems*.
#' MIT Press.
#'
#' @seealso
#' [met_alpha_rc_stream()] for single-design construction without optimisation.
#' [met_evaluate_alpha_efficiency()] for standalone criterion evaluation on an
#' existing field book.
#' [met_optimize_famoptg()] for the equivalent optimizer for
#' [met_prep_famoptg()] designs (RS only).
#'
#' @examples
#' ## -- Random Restart: fixed effects, A-criterion -----------------------------
#' result_rs <- met_optimize_alpha_rc(
#'   check_treatments   = c("CHK1", "CHK2", "CHK3"),
#'   check_families     = c("CHECK", "CHECK", "CHECK"),
#'   entry_treatments   = paste0("G", 1:167),
#'   entry_families     = rep(paste0("F", 1:7), length.out = 167),
#'   n_reps             = 3,
#'   n_rows             = 30,
#'   n_cols             = 20,
#'   min_block_size     = 19,
#'   max_block_size     = 20,
#'   treatment_effect   = "fixed",
#'   residual_structure = "AR1xAR1",
#'   rho_row            = 0.10,
#'   rho_col            = 0.10,
#'   method             = "RS",
#'   criterion          = "A",
#'   n_restarts         = 50
#' )
#'
#' result_rs$efficiency$A_criterion      # best A-criterion found
#' result_rs$optimization$best_score     # same value, lower is better
#' result_rs$optimization$score_history  # per-restart scores
#' result_rs$optimization$n_failed       # number of failed restarts
#'
#' \dontrun{
#' ## -- Simulated Annealing: random effects, CDmean ----------------------------
#' result_sa <- met_optimize_alpha_rc(
#'   check_treatments   = c("CHK1", "CHK2", "CHK3"),
#'   check_families     = c("CHECK", "CHECK", "CHECK"),
#'   entry_treatments   = paste0("G", 1:167),
#'   entry_families     = rep(paste0("F", 1:7), length.out = 167),
#'   n_reps             = 3,
#'   n_rows             = 30,
#'   n_cols             = 20,
#'   min_block_size     = 19,
#'   max_block_size     = 20,
#'   treatment_effect   = "random",
#'   prediction_type    = "GBLUP",
#'   K                  = my_kinship_matrix,
#'   varcomp            = list(
#'     sigma_g2   = 0.4, sigma_e2   = 0.6,
#'     sigma_rep2 = 0.1, sigma_ib2  = 0.05,
#'     sigma_r2   = 0.02, sigma_c2  = 0.02
#'   ),
#'   method             = "SA",
#'   criterion          = "CDmean",
#'   n_restarts         = 5,
#'   sa_max_iter        = 500,
#'   sa_temp_start      = 0.05,
#'   sa_temp_end        = 0.001,
#'   sa_cooling         = "exponential",
#'   sa_swap_scope      = "global",
#'   max_failure_rate_sa = 0.3
#' )
#'
#' result_sa$efficiency$CDmean           # mean prediction reliability [0, 1]
#' result_sa$optimization$best_score     # positive CDmean, higher is better
#' result_sa$optimization$n_failed       # failed SA initial designs
#'
#' ## -- Genetic Algorithm: fixed effects, D-criterion --------------------------
#' result_ga <- met_optimize_alpha_rc(
#'   check_treatments   = c("CHK1", "CHK2", "CHK3"),
#'   check_families     = c("CHECK", "CHECK", "CHECK"),
#'   entry_treatments   = paste0("G", 1:167),
#'   entry_families     = rep(paste0("F", 1:7), length.out = 167),
#'   n_reps             = 3,
#'   n_rows             = 30,
#'   n_cols             = 20,
#'   min_block_size     = 19,
#'   max_block_size     = 20,
#'   treatment_effect   = "fixed",
#'   residual_structure = "AR1xAR1",
#'   rho_row            = 0.10,
#'   rho_col            = 0.10,
#'   method             = "GA",
#'   criterion          = "D",
#'   n_restarts         = 3,
#'   ga_pop_size        = 20,
#'   ga_n_generations   = 50,
#'   ga_crossover_rate  = 0.7,
#'   ga_mutation_rate   = 0.2,
#'   ga_elitism         = 2,
#'   ga_invalid_retries = 3
#' )
#'
#' result_ga$efficiency$D_criterion      # best D-criterion, lower is better
#' result_ga$optimization$score_history  # per-generation best D-criterion
#' result_ga$optimization$n_failed       # total invalid offspring
#' }
#'
#' @importFrom stats runif
#' @export
met_optimize_alpha_rc <- function(

    # -- Design construction arguments (forwarded to met_alpha_rc_stream) --------
    check_treatments,
    check_families,
    entry_treatments,
    entry_families,
    n_reps,
    n_rows,
    n_cols,
    order                  = "column",
    serpentine             = FALSE,
    seed                   = NULL,
    attempts               = 5000,
    warn_and_correct       = TRUE,
    fix_rows               = TRUE,
    cluster_source         = c("Family", "GRM", "A"),
    GRM                    = NULL,
    A                      = NULL,
    id_map                 = NULL,
    cluster_method         = c("kmeans", "hclust"),
    cluster_seed           = 1,
    cluster_attempts       = 25,
    n_pcs_use              = Inf,
    n_blocks_per_rep       = NULL,
    min_block_size         = NULL,
    max_block_size         = NULL,
    check_placement        = c("systematic", "random"),
    check_position_pattern = c("spread", "corners_first"),
    use_dispersion         = FALSE,
    dispersion_source      = c("K", "A", "GRM"),
    dispersion_radius      = 1,
    dispersion_iters       = 2000,
    dispersion_seed        = 1,
    K                      = NULL,
    line_id_map            = NULL,

    # -- Efficiency evaluation arguments (forwarded to met_evaluate_alpha_efficiency) --
    treatment_effect   = c("random", "fixed"),
    prediction_type    = c("IID", "GBLUP", "PBLUP", "none"),
    check_as_fixed     = TRUE,
    residual_structure = c("IID", "AR1", "AR1xAR1"),
    rho_row            = 0,
    rho_col            = 0,
    varcomp            = list(
      sigma_e2   = 1,
      sigma_g2   = 1,
      sigma_rep2 = 1,
      sigma_ib2  = 1,
      sigma_r2   = 1,
      sigma_c2   = 1
    ),
    spatial_engine     = c("auto", "sparse", "dense"),
    dense_max_n        = 5000,
    eff_trace_samples  = 80,
    eff_full_max       = 400,

    # -- Optimizer arguments ---------------------------------------------------
    method    = c("RS", "SA", "GA"),
    criterion = c("A", "D", "both", "CDmean"),

    # RS
    n_restarts = 50L,

    # SA
    sa_max_iter   = 1000L,
    sa_temp_start = 1.0,
    sa_temp_end   = 0.001,
    sa_cooling    = c("exponential", "linear"),
    sa_swap_scope = c("global", "within_rep", "within_block"),

    # GA
    ga_pop_size       = 20L,
    ga_n_generations  = 50L,
    ga_crossover_rate = 0.7,
    ga_mutation_rate  = 0.2,
    ga_elitism        = 2L,

    # Failure thresholds
    max_failure_rate_rs = 0.5,   # stop if > 50% of RS restarts fail
    max_failure_rate_sa = 0.2,   # warn if > 20% of SA swap proposals fail
    ga_invalid_retries  = 3L,    # retries for invalid GA offspring

    # Verbosity
    verbose_opt = TRUE
) {

  # -- Argument matching -------------------------------------------------------
  method             <- match.arg(method)
  criterion          <- match.arg(criterion)
  treatment_effect   <- match.arg(treatment_effect)
  prediction_type    <- match.arg(prediction_type)
  cluster_source     <- match.arg(cluster_source)
  cluster_method     <- match.arg(cluster_method)
  residual_structure <- match.arg(residual_structure)
  spatial_engine     <- match.arg(spatial_engine)
  check_placement    <- match.arg(check_placement)
  check_position_pattern <- match.arg(check_position_pattern)
  dispersion_source  <- match.arg(dispersion_source)
  sa_cooling         <- match.arg(sa_cooling)
  sa_swap_scope      <- match.arg(sa_swap_scope)

  # -- Pre-flight: validate criterion / model compatibility -------------------
  if (treatment_effect == "random" && prediction_type == "none") {
    stop(paste0(
      "Cannot optimise: treatment_effect = 'random' and prediction_type = 'none' ",
      "produces no estimable efficiency criterion.\n",
      "Set treatment_effect = 'fixed', or choose prediction_type in c('IID','GBLUP','PBLUP')."
    ))
  }
  if (criterion %in% c("D", "both") && treatment_effect == "random") {
    warning(paste0(
      "D-criterion is not computed for random treatment effects (only A/PEV is available). ",
      "criterion will fall back to 'A' for random effect models."
    ))
  }
  if (criterion == "CDmean" && treatment_effect == "fixed") {
    stop(paste0(
      "criterion = 'CDmean' requires treatment_effect = 'random'. ",
      "CDmean is only defined for random treatment / genomic prediction models."
    ))
  }
  if (criterion == "CDmean" && prediction_type == "none") {
    stop("criterion = 'CDmean' requires prediction_type in c('IID', 'GBLUP', 'PBLUP').")
  }

  # -- Validate optimizer-specific arguments ----------------------------------
  if (n_restarts < 1L) stop("n_restarts must be >= 1.")
  if (method == "SA") {
    if (sa_max_iter < 1L)         stop("sa_max_iter must be >= 1.")
    if (sa_temp_start <= 0)       stop("sa_temp_start must be > 0.")
    if (sa_temp_end   <= 0)       stop("sa_temp_end must be > 0.")
    if (sa_temp_end >= sa_temp_start) stop("sa_temp_end must be < sa_temp_start.")
  }
  if (method == "GA") {
    if (ga_pop_size < 4L)         stop("ga_pop_size must be >= 4.")
    if (ga_n_generations < 1L)    stop("ga_n_generations must be >= 1.")
    if (ga_crossover_rate < 0 || ga_crossover_rate > 1)
      stop("ga_crossover_rate must be in [0,1].")
    if (ga_mutation_rate  < 0 || ga_mutation_rate  > 1)
      stop("ga_mutation_rate must be in [0,1].")
    if (ga_elitism < 0 || ga_elitism >= ga_pop_size)
      stop("ga_elitism must be in [0, ga_pop_size).")
  }

  # -- Master seed -------------------------------------------------------------
  master_seed <- if (is.null(seed)) sample.int(.Machine$integer.max, 1) else seed
  set.seed(master_seed)

  # -- Shared construction arguments ------------------------------------------
  build_args <- list(
    check_treatments       = check_treatments,
    check_families         = check_families,
    entry_treatments       = entry_treatments,
    entry_families         = entry_families,
    n_reps                 = n_reps,
    n_rows                 = n_rows,
    n_cols                 = n_cols,
    order                  = order,
    serpentine             = serpentine,
    attempts               = attempts,
    warn_and_correct       = warn_and_correct,
    fix_rows               = fix_rows,
    cluster_source         = cluster_source,
    GRM                    = GRM,
    A                      = A,
    id_map                 = id_map,
    cluster_method         = cluster_method,
    cluster_seed           = cluster_seed,
    cluster_attempts       = cluster_attempts,
    n_pcs_use              = n_pcs_use,
    n_blocks_per_rep       = n_blocks_per_rep,
    min_block_size         = min_block_size,
    max_block_size         = max_block_size,
    check_placement        = check_placement,
    check_position_pattern = check_position_pattern,
    use_dispersion         = use_dispersion,
    dispersion_source      = dispersion_source,
    dispersion_radius      = dispersion_radius,
    dispersion_iters       = dispersion_iters,
    dispersion_seed        = dispersion_seed,
    K                      = K,
    line_id_map            = line_id_map,
    verbose                = FALSE
  )

  # -- Shared evaluation arguments ---------------------------------------------
  eval_args <- list(
    n_rows             = n_rows,
    n_cols             = n_cols,
    check_treatments   = check_treatments,
    treatment_effect   = treatment_effect,
    prediction_type    = prediction_type,
    check_as_fixed     = check_as_fixed,
    residual_structure = residual_structure,
    rho_row            = rho_row,
    rho_col            = rho_col,
    varcomp            = varcomp,
    K                  = K,
    line_id_map        = line_id_map,
    spatial_engine     = spatial_engine,
    dense_max_n        = dense_max_n,
    eff_trace_samples  = eff_trace_samples,
    eff_full_max       = eff_full_max
  )

  # -- Criterion extraction (lower = better internally) -----------------------
  # A, D, both  : criterion values are already lower-is-better.
  # CDmean      : higher-is-better so negated internally.
  #               best_score and score_history are reported as positive CDmean.
  extract_score <- function(eff) {
    if (is.null(eff)) return(NA_real_)
    a_val  <- if (!is.null(eff$A_criterion)) eff$A_criterion else NA_real_
    d_val  <- if (!is.null(eff$D_criterion)) eff$D_criterion else NA_real_
    cd_val <- if (!is.null(eff$CDmean))      eff$CDmean      else NA_real_

    if (criterion == "A") return(a_val)

    if (criterion == "D") {
      if (is.na(d_val)) {
        warning("D_criterion is NA for this design; falling back to A_criterion.")
        return(a_val)
      }
      return(d_val)
    }

    if (criterion == "CDmean") {
      if (is.na(cd_val)) {
        warning("CDmean is NA for this design; falling back to A_criterion.")
        return(a_val)
      }
      return(-cd_val)
    }

    # "both": mean of available lower-is-better criteria
    vals <- c(a_val, d_val); vals <- vals[!is.na(vals)]
    if (length(vals) == 0) return(NA_real_)
    mean(vals)
  }

  # ============================================================
  # INTEGRITY CHECK
  # ============================================================
  # Validates a design against three structural constraints:
  #   1. No entry appears more than once within any replicate
  #   2. All expected entries are present in the field book
  #   3. All check treatments are present and correctly flagged
  #
  # Returns TRUE (valid) or FALSE (invalid, with a warning message).
  # Called immediately after construction and again before the final return.
  # ============================================================
  .check_design_integrity <- function(design, active_entries) {
    fb   <- design$field_book
    used <- fb[!is.na(fb$Treatment) & !as.logical(fb$Check), , drop = FALSE]

    # 1. No duplicate entries within any replicate
    if (nrow(used) > 0) {
      entry_counts <- table(used$Rep, used$Treatment)
      if (any(entry_counts > 1)) {
        warning(paste0(
          "[met_optimize_alpha_rc] Integrity check failed: duplicate entry ",
          "within a replicate. Design discarded."
        ))
        return(FALSE)
      }
    }

    # 2. All expected entries present
    present         <- unique(used$Treatment)
    missing_entries <- setdiff(active_entries, present)
    if (length(missing_entries) > 0) {
      warning(paste0(
        "[met_optimize_alpha_rc] Integrity check failed: ",
        length(missing_entries), " entr",
        if (length(missing_entries) == 1L) "y" else "ies",
        " missing from field book (",
        paste(head(missing_entries, 3), collapse = ", "),
        if (length(missing_entries) > 3L) ", ..." else "",
        "). Design discarded."
      ))
      return(FALSE)
    }

    # 3. All checks present and correctly flagged
    check_plots    <- fb[as.logical(fb$Check) & !is.na(fb$Treatment), , drop = FALSE]
    checks_found   <- unique(check_plots$Treatment)
    missing_checks <- setdiff(check_treatments, checks_found)
    if (length(missing_checks) > 0) {
      warning(paste0(
        "[met_optimize_alpha_rc] Integrity check failed: check treatment(s) ",
        paste(missing_checks, collapse = ", "),
        " not found as checks in field book. Design discarded."
      ))
      return(FALSE)
    }

    TRUE
  }

  # ============================================================
  # EMERGENCY FALLBACK
  # ============================================================
  # Called when no valid optimised design was found.
  # Attempts up to 10 fresh random constructions. Returns the
  # first one that passes integrity, or stops with a clear message.
  # ============================================================
  .emergency_fallback <- function() {
    warning(paste0(
      "[met_optimize_alpha_rc] No valid optimised design found across all ",
      "iterations. Attempting emergency fallback: generating a single ",
      "randomly constructed valid design."
    ))
    for (attempt in seq_len(10L)) {
      s        <- sample.int(.Machine$integer.max, 1)
      fallback <- run_pipeline(s)
      if (!is.null(fallback) && !is.na(fallback$score)) {
        warning(paste0(
          "[optimize_alpha_rc] Emergency fallback succeeded on attempt ",
          attempt, ". Returning a non-optimised valid design. ",
          "Consider increasing n_restarts or relaxing block size constraints."
        ))
        return(fallback)
      }
    }
    stop(paste0(
      "[optimize_alpha_rc] Emergency fallback failed after 10 attempts. ",
      "The design parameters may be infeasible. ",
      "Check n_rows, n_cols, n_reps, min_block_size, and max_block_size."
    ))
  }

  # ============================================================
  # PIPELINE: construct + integrity check + evaluate
  # ============================================================
  run_pipeline <- function(s, entry_perm = NULL) {
    args      <- build_args
    args$seed <- s

    active_entries <- if (!is.null(entry_perm)) {
      entry_treatments[entry_perm]
    } else {
      entry_treatments
    }

    if (!is.null(entry_perm)) {
      args$entry_treatments <- active_entries
      args$entry_families   <- entry_families[entry_perm]
    }

    design <- tryCatch(do.call(met_alpha_rc_stream, args), error = function(e) NULL)
    if (is.null(design)) return(NULL)

    # Integrity check: discard before scoring if constraints violated
    if (!.check_design_integrity(design, active_entries)) return(NULL)

    ea            <- eval_args
    ea$field_book <- design$field_book
    eff   <- tryCatch(do.call(met_evaluate_alpha_efficiency, ea), error = function(e) NULL)
    score <- extract_score(eff)

    list(design = design, efficiency = eff, score = score, seed = s,
         perm = entry_perm)
  }

  # ============================================================
  # SAFE BEST UPDATE
  # ============================================================
  # Updates the running best only when:
  #   (a) candidate is non-NULL with a valid score
  #   (b) score improves on current best
  #   (c) final integrity re-check passes
  # Returns the updated best (or unchanged best if conditions not met).
  # ============================================================
  .update_best <- function(best, best_score, cand) {
    if (is.null(cand) || is.na(cand$score)) return(list(best = best, best_score = best_score))
    if (cand$score >= best_score)            return(list(best = best, best_score = best_score))

    active <- if (!is.null(cand$perm)) entry_treatments[cand$perm] else entry_treatments
    if (!.check_design_integrity(cand$design, active)) {
      warning(paste0(
        "[met_optimize_alpha_rc] Candidate passed initial integrity check but ",
        "failed re-check at best-update stage. Candidate discarded."
      ))
      return(list(best = best, best_score = best_score))
    }

    list(best = cand, best_score = cand$score)
  }

  # ============================================================
  # METHOD 1: RANDOM RESTART (RS)
  # ============================================================
  run_RS <- function() {
    if (verbose_opt) message(sprintf(
      "[met_optimize_alpha_rc RS] %d restarts | criterion = '%s'", n_restarts, criterion
    ))

    best       <- NULL
    best_score <- Inf
    scores     <- rep(NA_real_, n_restarts)
    n_failed   <- 0L

    for (i in seq_len(n_restarts)) {
      s    <- sample.int(.Machine$integer.max, 1)
      cand <- run_pipeline(s)
      sc   <- if (is.null(cand)) NA_real_ else cand$score
      scores[i] <- sc

      if (is.null(cand) || is.na(sc)) {
        n_failed <- n_failed + 1L
      } else {
        upd <- .update_best(best, best_score, cand)
        best <- upd$best; best_score <- upd$best_score
      }

      if (verbose_opt) message(sprintf(
        "  [RS] %d/%d | score = %s | best = %s%s",
        i, n_restarts,
        ifelse(is.na(sc), "FAILED", sprintf("%.6f", sc)),
        ifelse(is.infinite(best_score), "none yet", sprintf("%.6f", best_score)),
        if (is.null(cand)) " [integrity/construction failed]" else ""
      ))
    }

    # Report failure rate
    if (n_failed > 0L) {
      rate <- n_failed / n_restarts
      msg  <- sprintf(
        "[RS] %d/%d restarts failed construction or integrity check (%.0f%%).",
        n_failed, n_restarts, 100 * rate
      )
      if (rate > max_failure_rate_rs) {
        stop(paste0(
          msg, "\nFailure rate exceeds threshold (", round(100 * max_failure_rate_rs), "%). ",
          "This likely indicates a systematic problem. Check n_rows, n_cols, ",
          "n_reps, min_block_size, and max_block_size."
        ))
      } else {
        warning(msg)
      }
    }

    list(best = best, scores = scores, n_failed = n_failed)
  }

  # ============================================================
  # METHOD 2: SIMULATED ANNEALING (SA)
  # ============================================================
  propose_swap <- function(perm, fb, scope) {
    n <- length(perm); if (n < 2) return(perm)

    get_movable_trts <- function(subset_rows) {
      unique(fb$Treatment[subset_rows & !fb$Check & !is.na(fb$Treatment)])
    }

    chosen <- switch(scope,
      "global" = {
        entry_treatments[perm][sample.int(n, 2)]
      },
      "within_rep" = {
        reps <- unique(fb$Rep[!fb$Check & !is.na(fb$Treatment)])
        r    <- sample(reps, 1)
        trts <- get_movable_trts(fb$Rep == r)
        if (length(trts) < 2) return(perm)
        sample(trts, 2)
      },
      "within_block" = {
        blks <- unique(fb$IBlock[!fb$Check & !is.na(fb$Treatment)])
        b    <- sample(blks, 1)
        trts <- get_movable_trts(fb$IBlock == b)
        if (length(trts) < 2) return(perm)
        sample(trts, 2)
      }
    )

    idx <- match(chosen, entry_treatments[perm])
    if (anyNA(idx)) return(perm)
    new_perm      <- perm
    new_perm[idx] <- perm[rev(idx)]
    new_perm
  }

  run_SA <- function() {
    if (verbose_opt) message(sprintf(
      "[SA] %d restarts x %d iters | scope = '%s' | cooling = '%s' | criterion = '%s'",
      n_restarts, sa_max_iter, sa_swap_scope, sa_cooling, criterion
    ))

    temp_schedule <- if (sa_cooling == "exponential") {
      alpha_c <- (sa_temp_end / sa_temp_start)^(1 / sa_max_iter)
      sa_temp_start * alpha_c^(seq_len(sa_max_iter) - 1)
    } else {
      seq(sa_temp_start, sa_temp_end, length.out = sa_max_iter)
    }

    global_best       <- NULL
    global_best_score <- Inf
    all_scores        <- vector("list", n_restarts)
    inner_seed        <- sample.int(.Machine$integer.max, 1)
    n_failed_restarts <- 0L

    for (restart in seq_len(n_restarts)) {
      if (verbose_opt) message(sprintf("  [SA] restart %d/%d", restart, n_restarts))

      init_seed <- sample.int(.Machine$integer.max, 1)
      current   <- run_pipeline(init_seed)

      if (is.null(current) || is.na(current$score)) {
        n_failed_restarts <- n_failed_restarts + 1L
        if (verbose_opt) message(
          "    [SA] initial design failed - restart skipped."
        )
        next
      }

      current_perm    <- seq_along(entry_treatments)
      current_score   <- current$score
      best_perm_r     <- current_perm
      best_score_r    <- current_score
      r_scores        <- numeric(sa_max_iter)
      n_invalid_swaps <- 0L

      for (iter in seq_len(sa_max_iter)) {
        temp     <- temp_schedule[iter]
        new_perm <- propose_swap(current_perm, current$design$field_book, sa_swap_scope)
        cand     <- run_pipeline(inner_seed, entry_perm = new_perm)

        if (is.null(cand) || is.na(cand$score)) {
          # Invalid swap candidate - keep current state unchanged.
          # Do NOT count as a Metropolis rejection; do NOT update temperature
          # bookkeeping. This prevents invalid proposals from distorting
          # the acceptance rate.
          n_invalid_swaps <- n_invalid_swaps + 1L
          r_scores[iter]  <- current_score
          next
        }

        # Metropolis acceptance
        delta  <- cand$score - current_score
        accept <- (delta < 0) || (runif(1) < exp(-delta / temp))
        if (accept) {
          current_perm  <- new_perm
          current_score <- cand$score
          current       <- cand
        }

        r_scores[iter] <- current_score

        # Update restart-level best via safe updater
        if (current_score < best_score_r) {
          best_score_r <- current_score
          best_perm_r  <- current_perm
        }
      }

      # Warn if too many invalid swaps in this restart
      invalid_rate <- n_invalid_swaps / sa_max_iter
      if (invalid_rate > max_failure_rate_sa) {
        warning(sprintf(
          "[SA] restart %d: %.0f%% of swap proposals produced invalid designs. ",
          restart, 100 * invalid_rate,
          "Consider 'global' swap scope or checking block size constraints."
        ))
      }

      all_scores[[restart]] <- r_scores

      if (verbose_opt) message(sprintf(
        "    [SA] restart %d done | best this restart = %.6f | invalid swaps = %d/%d | global best = %s",
        restart, best_score_r,
        n_invalid_swaps, sa_max_iter,
        ifelse(is.infinite(global_best_score), "none yet",
               sprintf("%.6f", global_best_score))
      ))

      # Regenerate the best design from this restart and update global best
      if (best_score_r < global_best_score) {
        final_cand <- run_pipeline(inner_seed, entry_perm = best_perm_r)
        upd        <- .update_best(global_best, global_best_score, final_cand)
        if (!is.null(upd$best) && upd$best_score < global_best_score) {
          global_best       <- upd$best
          global_best_score <- upd$best_score
        }
      }
    }

    # Report restart failure rate
    if (n_failed_restarts > 0L) {
      rate <- n_failed_restarts / n_restarts
      msg  <- sprintf(
        "[SA] %d/%d restarts failed to produce a valid initial design (%.0f%%).",
        n_failed_restarts, n_restarts, 100 * rate
      )
      if (rate > max_failure_rate_rs) {
        stop(paste0(
          msg, "\nFailure rate exceeds threshold. ",
          "Check n_rows, n_cols, n_reps, min_block_size, max_block_size."
        ))
      } else {
        warning(msg)
      }
    }

    list(best = global_best, scores = all_scores, n_failed = n_failed_restarts)
  }

  # ============================================================
  # METHOD 3: GENETIC ALGORITHM (GA)
  # ============================================================
  ox1_crossover <- function(p1, p2) {
    n   <- length(p1)
    pts <- sort(sample.int(n, 2)); a <- pts[1]; b <- pts[2]
    child <- rep(NA_integer_, n)
    child[a:b] <- p1[a:b]
    remaining  <- p2[!p2 %in% child[a:b]]
    fill_pos   <- c((b + 1):n, 1:(a - 1))
    fill_pos   <- fill_pos[fill_pos >= 1 & fill_pos <= n]
    child[fill_pos] <- remaining
    child
  }

  mutate_perm <- function(perm) {
    idx <- sample.int(length(perm), 2)
    perm[idx] <- perm[rev(idx)]
    perm
  }

  tournament_select <- function(fitness_vec, size = 2) {
    cc <- sample.int(length(fitness_vec), size, replace = FALSE)
    cc[which.min(fitness_vec[cc])]
  }

  run_GA <- function() {
    if (verbose_opt) message(sprintf(
      "[GA] pop = %d | generations = %d | crossover = %.2f | mutation = %.2f | elitism = %d | criterion = '%s'",
      ga_pop_size, ga_n_generations, ga_crossover_rate, ga_mutation_rate,
      ga_elitism, criterion
    ))

    n_ent      <- length(entry_treatments)
    inner_seed <- sample.int(.Machine$integer.max, 1)

    # -- Initialise population ----------------------------------------------
    if (verbose_opt) message("  [GA] Initialising population ...")
    population <- lapply(seq_len(ga_pop_size), function(i) {
      perm <- sample.int(n_ent)
      run_pipeline(inner_seed, entry_perm = perm)
    })

    # Replace any NULL slots with fresh random attempts
    for (i in seq_along(population)) {
      if (is.null(population[[i]])) {
        for (retry in seq_len(ga_invalid_retries)) {
          fresh <- run_pipeline(inner_seed, entry_perm = sample.int(n_ent))
          if (!is.null(fresh)) { population[[i]] <- fresh; break }
        }
      }
    }

    fitness <- sapply(population, function(x) {
      if (is.null(x) || is.na(x$score)) Inf else x$score
    })

    # Check initial population has at least one valid individual
    if (all(is.infinite(fitness))) {
      stop(paste0(
        "[GA] Initial population contains no valid designs. ",
        "Check n_rows, n_cols, n_reps, min_block_size, max_block_size."
      ))
    }

    global_best       <- NULL
    global_best_score <- Inf
    gen_scores        <- numeric(ga_n_generations)
    n_invalid_total   <- 0L

    # Initialise global best from population
    best_idx <- which.min(fitness)
    upd      <- .update_best(NULL, Inf, population[[best_idx]])
    global_best       <- upd$best
    global_best_score <- upd$best_score

    if (verbose_opt) message(sprintf(
      "  [GA] Initial best = %s",
      ifelse(is.infinite(global_best_score), "none valid",
             sprintf("%.6f", global_best_score))
    ))

    # -- Evolution loop -----------------------------------------------------
    for (gen in seq_len(ga_n_generations)) {
      ord        <- order(fitness)
      population <- population[ord]
      fitness    <- fitness[ord]

      # Carry elite individuals forward unchanged
      new_pop <- population[seq_len(ga_elitism)]
      new_fit <- fitness[seq_len(ga_elitism)]

      for (k in seq_len(ga_pop_size - ga_elitism)) {

        # Selection - skip NULL individuals in tournament
        valid_idx <- which(is.finite(fitness))
        if (length(valid_idx) < 2) valid_idx <- seq_along(fitness)
        p1_idx <- valid_idx[tournament_select(fitness[valid_idx])]
        p2_idx <- valid_idx[tournament_select(fitness[valid_idx])]

        p1 <- if (!is.null(population[[p1_idx]])) population[[p1_idx]]$perm else sample.int(n_ent)
        p2 <- if (!is.null(population[[p2_idx]])) population[[p2_idx]]$perm else sample.int(n_ent)
        if (is.null(p1)) p1 <- sample.int(n_ent)
        if (is.null(p2)) p2 <- sample.int(n_ent)

        # Crossover and mutation
        child_perm <- if (runif(1) < ga_crossover_rate) ox1_crossover(p1, p2) else p1
        if (runif(1) < ga_mutation_rate) child_perm <- mutate_perm(child_perm)

        # Evaluate offspring - retry with fresh random permutation if invalid
        child <- run_pipeline(inner_seed, entry_perm = child_perm)
        if (is.null(child) || is.na(child$score)) {
          n_invalid_total <- n_invalid_total + 1L
          for (retry in seq_len(ga_invalid_retries)) {
            fresh_perm <- sample.int(n_ent)
            child      <- run_pipeline(inner_seed, entry_perm = fresh_perm)
            if (!is.null(child) && !is.na(child$score)) break
          }
        }

        new_pop[[ga_elitism + k]] <- child
        new_fit[ga_elitism + k]   <- if (!is.null(child) && !is.na(child$score))
          child$score else Inf
      }

      population <- new_pop
      fitness    <- new_fit

      # Update global best via safe updater
      gen_best_idx <- which.min(fitness)
      if (is.finite(fitness[gen_best_idx]) && !is.null(population[[gen_best_idx]])) {
        upd <- .update_best(global_best, global_best_score, population[[gen_best_idx]])
        global_best       <- upd$best
        global_best_score <- upd$best_score
      }

      gen_scores[gen] <- ifelse(is.finite(fitness[gen_best_idx]),
                                fitness[gen_best_idx], NA_real_)

      if (verbose_opt) message(sprintf(
        "  [GA] gen %d/%d | gen best = %s | global best = %s | invalid offspring = %d",
        gen, ga_n_generations,
        ifelse(is.infinite(fitness[gen_best_idx]), "NA",
               sprintf("%.6f", fitness[gen_best_idx])),
        ifelse(is.infinite(global_best_score), "none yet",
               sprintf("%.6f", global_best_score)),
        n_invalid_total
      ))
    }

    # Warn if many invalid offspring were produced
    total_offspring <- ga_n_generations * (ga_pop_size - ga_elitism)
    if (n_invalid_total > 0L) {
      warning(sprintf(
        "[GA] %d/%d offspring (%0.f%%) required fallback due to integrity failure.",
        n_invalid_total, total_offspring,
        100 * n_invalid_total / total_offspring
      ))
    }

    list(best = global_best, scores = gen_scores, n_invalid = n_invalid_total)
  }

  # ============================================================
  # DISPATCH
  # ============================================================
  if (verbose_opt) message(sprintf(
    "\n[optimize_alpha_rc] method = '%s' | criterion = '%s' | master seed = %d\n",
    method, criterion, master_seed
  ))

  opt <- switch(method, RS = run_RS(), SA = run_SA(), GA = run_GA())

  # ============================================================
  # FINAL INTEGRITY CHECK ON STORED BEST
  # ============================================================
  # Even though .update_best() re-checks integrity at every update,
  # this final check acts as an absolute last-resort safety net before
  # the design reaches the user.
  if (!is.null(opt$best) && !is.null(opt$best$design)) {
    final_active <- if (!is.null(opt$best$perm))
      entry_treatments[opt$best$perm] else entry_treatments

    if (!.check_design_integrity(opt$best$design, final_active)) {
      # The stored best failed the final check - this should never happen
      # if .update_best() is working correctly, but if it does we treat it
      # as if no valid design was found and fall through to the fallback.
      warning(paste0(
        "[met_optimize_alpha_rc] The stored best design failed the final integrity ",
        "check. Falling back to emergency design. Please report this as a bug."
      ))
      opt$best <- NULL
    }
  }

  # ============================================================
  # FALLBACK: no valid best found
  # ============================================================
  if (is.null(opt$best) || is.null(opt$best$design)) {
    opt$best <- .emergency_fallback()
  }

  # ============================================================
  # ASSEMBLE OUTPUT
  # ============================================================
  out            <- opt$best$design
  out$efficiency <- opt$best$efficiency

  reported_best_score <- if (criterion == "CDmean" && !is.na(opt$best$score))
    -opt$best$score else opt$best$score

  out$optimization <- list(
    method        = method,
    criterion     = criterion,
    best_score    = reported_best_score,
    score_history = if (criterion == "CDmean") {
      sc <- opt$scores
      if (is.numeric(sc)) -sc
      else lapply(sc, function(x) if (is.numeric(x)) -x else x)
    } else {
      opt$scores
    },
    master_seed   = master_seed,
    n_failed      = opt$n_failed %||% opt$n_invalid %||% NA_integer_,
    n_restarts    = if (method == "RS") n_restarts else NULL,
    sa_params     = if (method == "SA") list(
      n_restarts   = n_restarts, max_iter     = sa_max_iter,
      temp_start   = sa_temp_start, temp_end  = sa_temp_end,
      cooling      = sa_cooling, swap_scope   = sa_swap_scope
    ) else NULL,
    ga_params     = if (method == "GA") list(
      pop_size       = ga_pop_size,    n_generations  = ga_n_generations,
      crossover_rate = ga_crossover_rate, mutation_rate = ga_mutation_rate,
      elitism        = ga_elitism,     invalid_retries = ga_invalid_retries
    ) else NULL
  )

  if (verbose_opt) {
    score_display <- ifelse(is.na(reported_best_score), NaN, reported_best_score)
    direction     <- if (criterion == "CDmean") "higher is better" else "lower is better"
    message(sprintf(
      "\n[optimize_alpha_rc] Done. Best %s = %.6f (%s)\n",
      criterion, score_display, direction
    ))
  }

  out
}

# ------------------------------------------------------------------------------
# Null-coalescing operator for internal use
# Returns lhs if non-NULL, otherwise rhs
# ------------------------------------------------------------------------------
`%||%` <- function(lhs, rhs) if (!is.null(lhs)) lhs else rhs
